# Generated by Django 4.1.4 on 2023-01-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Project Title"),
                ),
                (
                    "project_private",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Public", "Public"),
                            ("Private", "Private"),
                            ("Limited", "Limited"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "project_lead",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("deadline_date", models.DateField(blank=True, null=True)),
                ("project_overview", models.TextField(blank=True, null=True)),
                ("client", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
            ],
        ),
    ]
