# Generated by Django 4.1.4 on 2023-01-04 11:32

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='case_reference',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='id', unique=True),
        ),
    ]
