# Generated by Django 4.1.4 on 2022-12-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='national_insuarance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
