# Generated by Django 4.1.4 on 2023-01-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="national_insuarance",
            new_name="national_insurance",
        ),
        migrations.AlterField(
            model_name="lead",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="postal_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="work_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
