# Generated by Django 4.1.4 on 2023-01-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0002_rename_national_insuarance_lead_national_insurance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="inspection_auditor_file",
            field=models.FileField(blank=True, null=True, upload_to="media"),
        ),
    ]
