# Generated by Django 4.1.4 on 2023-01-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0003_alter_lead_inspection_auditor_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="case_reference",
        ),
        migrations.AddField(
            model_name="lead",
            name="entry_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
